version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: 'Install system deps'
          command: 'sudo apt-get install openssl libssl-dev zlib1g zlib1g-dev libuv1 libuv1-dev'

      - run:
          name: 'Install/Update node modules'
          command: 'yarn'
      
      - run:
          name: 'Build project'
          command: 'yarn run build'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      # - run: yarn test